# yml 문법은 들여쓰기만 틀려도 오류나므로, 편집에 주의한다.
version: 2
# 빌드 작업을 수행한 job을 작성해 넣는다.
jobs:
  # job의 이름이다. build가 아니어도 상관없다. 아래의 workflows에서 실행할 때 사용된다.
  build:
    # 위에 언급한대로, 렌탈할 서버를 선택하는 부분이다.
    # docker 가상화 이미지를 설정할 수 있는데,
    # circleci에서 미리 빌드해놓은 제공된 이미지 목록에서 선택해야 한다.
    # 다음의 주소에서 선택할 수 있는 이미지를 확인할 수 있다. https://circleci.com/docs/2.0/circleci-images/
    docker:
      # npm 빌드를 해야하므로, nodejs로 설정했다.
      - image: circleci/node:latest
    steps:
      # 배포할 때 사용할 쉘 스크립트를 step별로 입력한다.
      # 소스를 checkout 하여, 리눅스 머신에 소스를 적용한다.
      - checkout
      # 의존성 설치
      - run: npm install
      # vue 빌드
      - run: npm run build
      # nginx 서버로 포팅 (참고로 이 접속정보는 없다.)
      - run: $ scp -r dist/. testuser@dkant.net:/usr/share/nginx/html/
#workflows에는 위에 선언한 job을 실행시킬 수 있다. 설정하기에 따라서는 병렬로 빌드하거나, 여러개의 job을 실행하는것도 가능하다.
workflows:
  version: 2
  build:
    jobs:
      # 위에서 작성한 job명칭을 입력한다.
      - build